#! /bin/sh

sxhkd &
urxvt &
panel &
feh --bg-fill ~/.wallpaper.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config normal_border_color  '#ffffff'
bspc config active_border_color  '#ffffff'
bspc config focused_border_color '#ffffff'

bspc config window_gap           15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
