#! /bin/sh

sxhkd &
xterm &
compton &
panel &
feh --bg-fill ~/.wallpaper.jpg &

bspc config border_width 10
bspc config normal_border_color '#312e3d'
bspc config active_border_color '#312e3d'
bspc config focused_border_color '#312e3d'

bspc config window_gap 40

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config history_aware_focus true

bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI1 -d VI VII VIII IX X
