#! /bin/sh

sxhkd &
compton &
urxvt &
feh --bg-fill ~/.wallpaper.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 5
bspc config window_gap 20

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true

bspc config normal_border_color '#775dff'
bspc config active_border_color '#775dff'
bspc config focused_border_color '#d8137f'

bspc rule -a Gimp state=floating follow=on
bspc rule -a astrogif state=floating
bspc rule -a torguard state=floating
