export ZSH="/Users/brendan/.oh-my-zsh"

CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"
ZSH_THEME="gallifrey"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8
export EDITOR='vim'

export GOPATH=$HOME/gospace
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/go/bin
export GOPRIVATE=gitlab.newnormalgroup.com/crystallize

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias zshconfig="vim ~/.zshrc"
alias reload="source ~/.zshrc"

alias gs="git status"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gcm="git commit -m"

alias dc="docker-compose"

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

export PATH="$PATH:`yarn global bin`"

alias tf="terraform"

export PATH=$PATH:"/home/$USER/.local/bin"
export PATH="$FLYCTL_INSTALL/bin:$PATH"
